// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/jit.proto

package jit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role            string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Justification   string                 `protobuf:"bytes,4,opt,name=justification,proto3" json:"justification,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccessRequest) Reset() {
	*x = AccessRequest{}
	mi := &file_proto_jit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequest) ProtoMessage() {}

func (x *AccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequest.ProtoReflect.Descriptor instead.
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_jit_proto_rawDescGZIP(), []int{0}
}

func (x *AccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccessRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AccessRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *AccessRequest) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

type AccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessResponse) Reset() {
	*x = AccessResponse{}
	mi := &file_proto_jit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessResponse) ProtoMessage() {}

func (x *AccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessResponse.ProtoReflect.Descriptor instead.
func (*AccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_jit_proto_rawDescGZIP(), []int{1}
}

func (x *AccessResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AccessResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_jit_proto protoreflect.FileDescriptor

const file_proto_jit_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/jit.proto\x12\x03jit\"\x8d\x01\n" +
	"\rAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12)\n" +
	"\x10duration_minutes\x18\x03 \x01(\x05R\x0fdurationMinutes\x12$\n" +
	"\rjustification\x18\x04 \x01(\tR\rjustification\"G\n" +
	"\x0eAccessResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2I\n" +
	"\rAccessService\x128\n" +
	"\rRequestAccess\x12\x12.jit.AccessRequest\x1a\x13.jit.AccessResponseB\x1cZ\x1ajit-grpc-starter/proto;jitb\x06proto3"

var (
	file_proto_jit_proto_rawDescOnce sync.Once
	file_proto_jit_proto_rawDescData []byte
)

func file_proto_jit_proto_rawDescGZIP() []byte {
	file_proto_jit_proto_rawDescOnce.Do(func() {
		file_proto_jit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_jit_proto_rawDesc), len(file_proto_jit_proto_rawDesc)))
	})
	return file_proto_jit_proto_rawDescData
}

var file_proto_jit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_jit_proto_goTypes = []any{
	(*AccessRequest)(nil),  // 0: jit.AccessRequest
	(*AccessResponse)(nil), // 1: jit.AccessResponse
}
var file_proto_jit_proto_depIdxs = []int32{
	0, // 0: jit.AccessService.RequestAccess:input_type -> jit.AccessRequest
	1, // 1: jit.AccessService.RequestAccess:output_type -> jit.AccessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_jit_proto_init() }
func file_proto_jit_proto_init() {
	if File_proto_jit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_jit_proto_rawDesc), len(file_proto_jit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_jit_proto_goTypes,
		DependencyIndexes: file_proto_jit_proto_depIdxs,
		MessageInfos:      file_proto_jit_proto_msgTypes,
	}.Build()
	File_proto_jit_proto = out.File
	file_proto_jit_proto_goTypes = nil
	file_proto_jit_proto_depIdxs = nil
}
